user_input=input("enter your name: ")
lenth=len(user_input)
search=user_input.find("i")
result=user_input.rfind("h")
is_num=user_input.isdigit()
is_letter=user_input.isalpha()
count=user_input.count("h")
change=user_input.replace("h","l")
print(count)
print(is_letter)
print(is_num)
print(lenth)
print(search)
print(result)
print(user_input.upper())
print(user_input.lower())
user_input=user_input.capitalize()
print(user_input)
print(change)

